categories:
- network
- sms
- location
- contacts
- storage
- telephony
- camera_media
- receiver
- component_exposure
- dynamic_loading
- crypto
- system_settings
permission_vocab:
- android.permission.internet
- android.permission.access_network_state
- android.permission.write_external_storage
- android.permission.wake_lock
- android.permission.access_wifi_state
- android.permission.read_external_storage
- android.permission.read_phone_state
- android.permission.vibrate
- android.permission.access_coarse_location
- android.permission.access_fine_location
- android.permission.receive_boot_completed
- android.permission.camera
- android.permission.get_tasks
- android.permission.change_wifi_state
- android.permission.system_alert_window
- com.google.android.c2dm.permission.receive
- android.permission.mount_unmount_filesystems
- android.permission.write_settings
- android.permission.change_network_state
- android.permission.record_audio
- com.google.android.finsky.permission.bind_get_install_referrer_service
- android.permission.foreground_service
- android.permission.bluetooth
- android.permission.get_accounts
- android.permission.read_logs
- android.permission.call_phone
- android.permission.modify_audio_settings
- android.permission.request_install_packages
- com.android.launcher.permission.install_shortcut
- android.permission.access_location_extra_commands
- com.huawei.android.launcher.permission.change_badge
- android.permission.read_contacts
- com.android.vending.billing
- android.permission.flashlight
- android.permission.bluetooth_admin
- android.permission.receive_user_present
- com.htc.launcher.permission.read_settings
- com.sec.android.provider.badge.permission.read
- com.sec.android.provider.badge.permission.write
- com.huawei.android.launcher.permission.read_settings
- com.sonyericsson.home.permission.broadcast_badge
- com.google.android.gms.permission.ad_id
- com.htc.launcher.permission.update_shortcut
- com.huawei.android.launcher.permission.write_settings
- com.oppo.launcher.permission.read_settings
- com.anddoes.launcher.permission.update_count
- com.majeur.launcher.permission.update_badge
- com.sonymobile.home.permission.provider_insert_badge
- android.permission.disable_keyguard
- android.permission.restart_packages
- android.permission.read_app_badge
- com.oppo.launcher.permission.write_settings
- android.permission.broadcast_sticky
- android.permission.send_sms
- com.android.launcher.permission.read_settings
- me.everything.badger.permission.badge_count_read
- me.everything.badger.permission.badge_count_write
- android.permission.manage_accounts
- android.permission.read_sms
- android.permission.receive_sms
- android.permission.change_configuration
- android.permission.post_notifications
- android.permission.kill_background_processes
- android.permission.use_credentials
- com.android.launcher.permission.uninstall_shortcut
- android.permission.download_without_notification
- android.permission.reorder_tasks
- com.google.android.providers.gsf.permission.read_gservices
- android.permission.set_wallpaper
- android.permission.write_contacts
- android.permission.use_fingerprint
- android.permission.write_sms
- android.permission.query_all_packages
- android.permission.write_calendar
- com.asus.msa.supplementarydid.access
- android.permission.broadcast_package_changed
- android.permission.broadcast_package_replaced
- com.coloros.mcs.permission.recieve_mcs_message
- android.permission.read_calendar
- android.permission.broadcast_package_added
- android.permission.broadcast_package_install
- com.android.browser.permission.read_history_bookmarks
- android.permission.read_settings
- android.permission.authenticate_accounts
- android.permission.process_outgoing_calls
- android.permission.change_wifi_multicast_state
- android.permission.access_download_manager
- android.permission.interact_across_users_full
- android.permission.expand_status_bar
- android.permission.system_overlay_window
- android.permission.access_background_location
- com.meizu.c2dm.permission.receive
- android.permission.battery_stats
- com.android.vending.check_license
- com.meizu.flyme.push.permission.receive
- com.android.alarm.permission.set_alarm
- android.permission.read_media_images
- android.permission.nfc
- com.google.android.gms.permission.activity_recognition
- android.permission.package_usage_stats
- com.heytap.mcs.permission.recieve_mcs_message
- android.permission.get_package_size
- android.permission.access_mock_location
- android.permission.write_apn_settings
- com.android.launcher.permission.write_settings
- android.permission.read_call_log
- android.permission.access_coarse_updates
- android.permission.request_ignore_battery_optimizations
- android.permission.access_adservices_attribution
- android.permission.read_media_video
- android.permission.set_debug_app
- com.huawei.appmarket.service.commondata.permission.get_common_data
- android.permission.access_adservices_ad_id
- android.permission.access_gps
- android.webkit.permission.plugin
- android.permission.use_biometric
- android.permission.schedule_exact_alarm
- android.permission.write_sync_settings
- android.permission.receive_mms
- com.vivo.notification.permission.badge_icon
- android.permission.install_packages
- android.permission.read_profile
- android.permission.set_wallpaper_hints
- android.permission.read_media_audio
- com.android.launcher3.permission.read_settings
- android.permission.write_internal_storage
- android.permission.baidu_location_service
- android.permission.read_sync_settings
intent_vocab:
- android.intent.action.main
- android.intent.category.launcher
- android.intent.category.default
- android.intent.action.view
- android.intent.action.boot_completed
- android.intent.category.browsable
- android.net.conn.connectivity_change
- com.google.android.c2dm.intent.receive
- android.intent.action.user_present
- com.android.vending.install_referrer
- com.google.firebase.messaging_event
- android.intent.action.action_power_connected
- android.intent.action.action_power_disconnected
- android.intent.action.package_removed
- android.intent.action.package_added
- android.intent.action.time_set
- com.google.firebase.instance_id_event
- android.intent.action.timezone_changed
- android.intent.action.battery_low
- android.intent.action.battery_okay
- android.intent.action.device_storage_low
- android.intent.action.device_storage_ok
- androidx.work.impl.background.systemalarm.updateproxies
- android.intent.action.quickboot_poweron
- com.sina.weibo.sdk.action.action_sdk_req_activity
- androidx.work.diagnostics.request_diagnostics
- android.intent.action.my_package_replaced
- com.facebook.sdk.action_current_access_token_changed
- cn.jpush.android.ui.pushactivity
- cn.jpush.android.intent.notification_received_proxy
- cn.jpush.android.intent.pushservice
- cn.jpush.android.intent.register
- cn.jpush.android.intent.report
- cn.jpush.android.intent.push_time
- com.xiaomi.mipush.receive_message
- com.xiaomi.mipush.error
- cn.jpush.android.intent.notification_opened
- cn.jpush.android.intent.message_received
- cn.jpush.android.intent.notification_received
- cn.jpush.android.intent.registration
- cn.jpush.android.intent.daemonservice
- com.xiaomi.mipush.message_arrived
- com.huawei.push.action.messaging_event
- cn.jpush.android.intent.connection
- com.huawei.android.push.intent.receive
- com.huawei.android.push.intent.registration
- com.xiaomi.push.ping_timer
- android.intent.action.media_mounted
- org.agoo.android.intent.action.receive
- android.intent.action.send
- com.huawei.intent.action.push
- com.google.android.c2dm.intent.registration
- android.intent.action.download_complete
- androidx.profileinstaller.action.install_profile
- android.intent.category.leanback_launcher
- org.android.agoo.client.messagereceiverservice
- androidx.profileinstaller.action.skip_file
- androidx.profileinstaller.action.save_profile
- androidx.profileinstaller.action.benchmark_operation
- com.taobao.accs.intent.action.receive
- com.taobao.accs.intent.action.command
- com.coloros.mcs.action.receive_mcs_message
- com.taobao.accs.intent.action.service
- com.htc.intent.action.quickboot_poweron
feature_vocab:
- android.hardware.camera
- android.hardware.camera.autofocus
- android.hardware.touchscreen
- android.hardware.touchscreen.multitouch
- android.hardware.touchscreen.multitouch.distinct
- android.hardware.location.gps
- android.hardware.camera.flash
- android.hardware.wifi
- android.hardware.camera.front
- android.hardware.telephony
- android.hardware.location.network
- android.hardware.screen.landscape
- android.hardware.location
- android.hardware.microphone
- android.hardware.sensor.accelerometer
- android.hardware.bluetooth_le
- android.hardware.bluetooth
- android.hardware.screen.portrait
- android.hardware.vulkan.version
- android.software.vr.mode
- android.software.leanback
- android.software.vr.high_performance
- android.hardware.nfc.hce
- android.hardware.vulkan
- android.hardware.nfc
- android.hardware.camera.any
- android.software.live_wallpaper
- android.hardware.autofocus
- android.hardware.camera2.full
- android.hardware.faketouch
- android.hardware.camera2
- android.hardware.usb.host
metadata:
  source_split: train
  leakage_guard: train_only
  num_records: 10334
